name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # This line allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Download and set up Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
        unzip commandlinetools-linux-8092744_latest.zip -d $HOME/android-sdk
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        find $HOME/android-sdk/cmdline-tools/* -maxdepth 0 -name 'latest' -prune -o -exec mv -t $HOME/android-sdk/cmdline-tools/latest {} +
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew android:assembleDebug
